# This is a basic workflow to help you get started with Actions

name: Create New Directory

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
    contents: write
    actions: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        name: Checkout Repo
      - name: create directory
        run : |
          rm -d demowf
          mkdir -p demowf
          echo "New Directory is created successfully" > demowf/README1.md
      - name: secret validation
        run: 
          echo "$GITHUB_TOKEN"
      - name: Commit and Push
        run: |
          git config --global user.name "RajeshAnugula"
          git config --global user.email "angularajesh.kumar@infosys.com"
          git add demowf/*
          git commit -m "Create new folder"
          git push
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: folder validation
        run: |
          if [-d "demowf"];then
            echo Folder demowf is created successfully;
          else
            echo Folder demowf doesnot exist;
            exit 1;
          fi
      
