# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os}}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [   18.x, 20.x, 22.x ]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
           node-version: ${{ matrix.node-version }}
      - run: npm init -y
      - run: npm install --verbose
      - run: npm run build --if-present --verbose
      - name: List files in .npm directory
        run: ls -la /home/runner/.npm/
  upload:
    runs-on: ${{ matrix.os }}
    needs: build
    steps:
      - uses: action/upload-artifact@v3
        name: Uploading build logs
        with:
          name: build log
          path: /home/runner/.npm/*
  
    
    
 
